# Root logger
log4j.rootCategory=ERROR, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Silence everything
log4j.logger.org.apache.spark=ERROR
log4j.logger.org.apache.hadoop=ERROR
log4j.logger.org.apache.kafka=ERROR
log4j.logger.io.delta=ERROR
log4j.logger.com.google=ERROR
log4j.logger.org.apache.ivy=OFF
log4j.logger.org.eclipse.jetty=ERROR
log4j.logger.py4j=ERROR